name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    # In use: Heroku-18 stack (Ubuntu 18.04)
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Test Application
        run: npm test
